In [5]:
import os
import pandas as pd
import pyarrow
import fastparquet
import glob

In [6]:
files_path = glob.glob("./dataset/raw/*.snappy.parquet")
files_path

['./dataset/raw\\part-00000-tid-2779033056155408584-f6316110-4c9a-4061-ae48-69b77c7c8c36-4-1-c000.snappy.parquet',
 './dataset/raw\\part-00000-tid-5196563791502273604-c90d3a24-52f2-4955-b4ec-fb143aae74d8-4-1-c000.snappy.parquet',
 './dataset/raw\\part-00000-tid-6364321654468257203-dc13a5d6-36ae-48c6-a018-37d8cfe34cf6-263-1-c000.snappy.parquet']

In [7]:
df_pdv = pd.read_parquet(files_path[0], engine="fastparquet")

In [11]:
df_pdv.memory_usage(deep=True)

Index               132
pdv              978684
premise          856924
categoria_pdv    854602
zipcode           57676
dtype: int64

In [8]:
df_transacao = pd.read_parquet(files_path[1], engine="fastparquet")

In [12]:
df_transacao.memory_usage(deep=True)

Index                        132
internal_store_id      445311839
internal_product_id    445351024
distributor_id         328227006
transaction_date        52485584
reference_date          52485584
quantity                52485584
gross_value             52485584
net_value               52485584
gross_profit            52485584
discount                52485584
taxes                   52485584
dtype: int64

In [9]:
df_produto = pd.read_parquet(files_path[2], engine="fastparquet")

In [13]:
df_produto.memory_usage(deep=True)

Index                   132
produto         13057825890
categoria       11241154473
descricao       16074011982
tipos           11615506119
label            9628312401
subcategoria    11424850308
marca           14664212688
fabricante      12750630792
dtype: int64

In [10]:
df_pdv

                       pdv      premise     categoria_pdv  zipcode
0      2204965430669363375   On Premise      Mexican Rest    30741
1      5211957289528622910   On Premise       Hotel/Motel    80011
2      9024493554530757353  Off Premise       Convenience    80751
3      8659197371382902429   On Premise        Restaurant    80439
4      1400854873763881130   On Premise        Restaurant    30093
...                    ...          ...               ...      ...
14414  5047149578012031122  Off Premise    Package/Liquor    81501
14415  8352177618955815208  Off Premise    Package/Liquor    80219
14416  7754182004766664314   On Premise     Special Event    81004
14417  9044929558186581877   On Premise  Other On Premise    81226
14418  8795399024619655297   On Premise               Bar    80205

[14419 rows x 4 columns]

In [77]:
df_pdv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14419 entries, 0 to 14418
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pdv            14419 non-null  object
 1   premise        14419 non-null  object
 2   categoria_pdv  14419 non-null  object
 3   zipcode        14419 non-null  int32
dtypes: int32(1), object(3)
memory usage: 394.4+ KB

In [78]:
df_pdv.describe(include="all")

                        pdv     premise categoria_pdv       zipcode
count                 14419       14419         14419  14419.000000
unique                14419           2            54           NaN
top     2204965430669363375  On Premise    Restaurant           NaN
freq                      1        8216          3316           NaN
mean                    NaN         NaN           NaN  62676.248769
std                     NaN         NaN           NaN  24052.659458
min                     NaN         NaN           NaN   8107.000000
25%                     NaN         NaN           NaN  30341.000000
50%                     NaN         NaN           NaN  80202.000000
75%                     NaN         NaN           NaN  80535.000000
max                     NaN         NaN           NaN  90920.000000

In [80]:
df_pdv.shape

(14419, 4)

In [81]:
df_pdv.dtypes

pdv              object
premise          object
categoria_pdv    object
zipcode           int32
dtype: object

In [84]:
df_transacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6560698 entries, 0 to 6560697
Data columns (total 11 columns):
 #   Column               Dtype
---  ------               -----
 0   internal_store_id    object
 1   internal_product_id  object
 2   distributor_id       object
 3   transaction_date     datetime64[ns]
 4   reference_date       datetime64[ns]
 5   quantity             float64
 6   gross_value          float64
 7   net_value            float64
 8   gross_profit         float64
 9   discount             float64
 10  taxes                float64
dtypes: datetime64[ns](2), float64(6), object(3)
memory usage: 550.6+ MB

In [85]:
df_transacao.describe(include='all')

,internal_store_id,internal_product_id,distributor_id,transaction_date,reference_date,quantity,gross_value,net_value,gross_profit,discount,taxes
count,6560698,6560698,6560698,6560698,6560698,6.560698e+06,6.560698e+06,6.560698e+06,6.560698e+06,6.560698e+06,6.560698e+06
unique,15086,7092,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,6421526591548961726,4623814317972718932,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,9657,108018,2842086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,2022-07-12 12:28:13.641744384,2022-06-27 22:47:38.466826752,8.125893e+00,1.227512e+02,1.191233e+02,2.193092e+01,2.766684e+01,3.627938e+00
min,NaN,NaN,NaN,2022-01-01 00:00:00,2022-01-01 00:00:00,-1.530000e+03,-4.267290e+04,-3.984800e+04,-2.743960e+05,-1.309680e+04,-4.099409e+03
25%,NaN,NaN,NaN,2022-04-20 00:00:00,2022-04-01 00:00:00,1.000000e+00,2.803500e+01,2.711032e+01,7.140242e+00,0.000000e+00,1.800000e-01
50%,NaN,NaN,NaN,2022-07-19 00:00:00,2022-07-01 00:00:00,2.000000e+00,4.210000e+01,4.077048e+01,1.051024e+01,2.300000e+00,5.400000e-01
75%,NaN,NaN,NaN,2022-10-03 00:00:00,2022-10-01 00:00:00,4.000000e+00,9.200000e+01,8.787900e+01,2.173200e+01,8.700000e+00,3.039677e+00
max,NaN,NaN,NaN,2022-12-31 00:00:00,2022-12-01 00:00:00,9.423000e+04,6.041739e+05,6.041739e+05,2.744160e+05,2.400830e+05,2.073238e+03
std,NaN,NaN,NaN,NaN,NaN,8.049387e+01,8.664265e+02,8.651757e+02,2.326470e+02,3.847624e+02,1.130985e+01

In [86]:
df_transacao.columns

Index(['internal_store_id', 'internal_product_id', 'distributor_id',
       'transaction_date', 'reference_date', 'quantity', 'gross_value',
       'net_value', 'gross_profit', 'discount', 'taxes'],
      dtype='object')

In [87]:
df_pdv_transacao = df_pdv.merge(df_transacao, left_on=['pdv'], right_on=['internal_store_id'], how='inner')
df_pdv_transacao

,pdv,premise,categoria_pdv,zipcode,internal_store_id,internal_product_id,distributor_id,transaction_date,reference_date,quantity,gross_value,net_value,gross_profit,discount,taxes
0,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,8654618855511723434,4,2022-05-10,2022-05-01,1.000000,19.990000,19.990000,5.990000,1.000000,0.000000
1,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,5168467358507505407,4,2022-08-01,2022-08-01,12.000000,52.799999,38.158596,7.188600,7.200000,14.641404
2,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,3262679882836704514,4,2022-08-01,2022-08-01,2.000000,47.200001,42.640484,12.474483,0.000000,4.559516
3,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,14523659809755688,4,2022-07-08,2022-07-01,1.000000,23.500000,22.584913,5.498246,2.800000,0.915087
4,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,2888002190098573554,4,2022-10-24,2022-10-01,1.000000,25.000000,25.000000,7.500000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6515111,8795399024619655297,On Premise,Bar,80205,8795399024619655297,2000299989413890957,5,2022-09-11,2022-09-01,11.000004,274.760103,274.760103,80.555031,12.790008,0.000000
6515112,8795399024619655297,On Premise,Bar,80205,8795399024619655297,6182078584966538293,5,2022-09-11,2022-09-01,1.000002,25.500051,25.500051,7.666683,0.000000,0.000000
6515113,8795399024619655297,On Premise,Bar,80205,8795399024619655297,5800966932260176140,5,2022-09-11,2022-09-01,1.999992,51.979794,51.979794,11.994953,5.259979,0.000000
6515114,8795399024619655297,On Premise,Bar,80205,8795399024619655297,813787524868611759,5,2022-09-11,2022-09-01,3.000000,18.929993,18.929993,3.622493,0.000000,0.000000
6515115,8795399024619655297,On Premise,Bar,80205,8795399024619655297,7891860100939313524,5,2022-09-11,2022-09-01,1.000002,28.000055,28.000055,5.416677,4.430009,0.000000

In [88]:
df_pdv_transacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6515116 entries, 0 to 6515115
Data columns (total 15 columns):
 #   Column               Dtype
---  ------               -----
 0   pdv                  object
 1   premise              object
 2   categoria_pdv        object
 3   zipcode              int32
 4   internal_store_id    object
 5   internal_product_id  object
 6   distributor_id       object
 7   transaction_date     datetime64[ns]
 8   reference_date       datetime64[ns]
 9   quantity             float64
 10  gross_value          float64
 11  net_value            float64
 12  gross_profit         float64
 13  discount             float64
 14  taxes                float64
dtypes: datetime64[ns](2), float64(6), int32(1), object(6)
memory usage: 720.7+ MB

In [89]:
df_produto

,produto,categoria,descricao,tipos,label,subcategoria,marca,fabricante
0,69753381296344216,Package,MONDAY NIGHT BREW DON'T CALL IT HOTLANTA 6/4/1...,Package,In&Out,Red Wine,Monday Night Don't Call It Hotlanta,Monday Night Brewing
1,5019314249828979377,Distilled Spirits,BARRELL V907 RED PHONE BOOTH & TOWER,Distilled Spirits,Specialty,Lager / Pilsner,Barrell Bourbon- Private Label,Barrell Craft Spirits
2,4016404282141162328,Distilled Spirits,DRINKWORKS SIMPLY REFRESHING GIN & TONIC 12/4/...,Distilled Spirits,Core,Lager,Drinkworks Simply Refreshing Gin & Tonic,AB Drinkworks
3,6217366559810422145,Distilled Spirits,CENZON REPOSADO 100% AGAVE 6/750ML 80PF,Distilled Spirits,None,Lager,Cenzon Reposado 100% Agave Tequila,Sazerac Spirits
4,7356488787409434558,Draft,REFORMATION STARK 1/4 KEG,Draft,Core,Red Wine,Reformation Stark,Reformation Brewery
...,...,...,...,...,...,...,...,...
192356311,2910976334046702887,ABA Spirits,SAZERAC OLD WESTBURY GIN WNBS 1LTR 42PRF,Wine > 14 %,Core,Lager,Old Westbury Extra Dry Gin,Sazerac ABA
192356312,997545005038320324,Package,TX RANCH WATER LIME 4/6 CN,Package,Core,Soda,TX Ranch Water Lime,MPL Brands NV/Patco
192356313,5342092316314076162,Draft,TANTRUM POEMS AT MIDNIGHT RASPBERRY BLACKBERRY...,Draft,Discontinued,Energy,Tantrum Poems at Midnight Raspberry Blackberry,Tantrum Brewing Co
192356314,8663495453589323322,Wine,SALVESTRIN RETTAGIO 2019,Wine > 14 %,Close Out,Lager,Salvestrin Rettagio,Salvestrin Wine Company
192356315,1933905639949913855,Distilled Spirits,STROUDWATER RYE,Distilled Spirits,Close Out,Lager,Stroudwater Rye,Northstar Brands

In [ ]:
df_produto.dtypes

produto         object
categoria       object
descricao       object
tipos           object
label           object
subcategoria    object
marca           object
fabricante      object
dtype: object

In [ ]:
df_produto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192356316 entries, 0 to 192356315
Data columns (total 8 columns):
 #   Column        Dtype
---  ------        -----
 0   produto       object
 1   categoria     object
 2   descricao     object
 3   tipos         object
 4   label         object
 5   subcategoria  object
 6   marca         object
 7   fabricante    object
dtypes: object(8)
memory usage: 11.5+ GB

In [ ]:
df_produto.describe(include='all')

,produto,categoria,descricao,tipos,label,subcategoria,marca,fabricante
count,192356316,192356316,192356316,192356316,152404137,192356316,192356316,192356316
unique,7092,7,7092,22,14,43,4221,343
top,69753381296344216,Distilled Spirits,MONDAY NIGHT BREW DON'T CALL IT HOTLANTA 6/4/1...,Distilled Spirits,Core,Red Wine,Barrell Bourbon- Private Label,Sazerac Spirits
freq,27123,59724846,27123,49255368,55602150,35580564,1627380,31706787

In [ ]:
df_produto.columns

Index(['produto', 'categoria', 'descricao', 'tipos', 'label', 'subcategoria',
       'marca', 'fabricante'],
      dtype='object')

In [ ]:
df_produto

,pdv,premise,categoria_pdv,zipcode,internal_store_id,internal_product_id,distributor_id,transaction_date,reference_date,quantity,gross_value,net_value,gross_profit,discount,taxes
0,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,8654618855511723434,4,2022-05-10,2022-05-01,1.000000,19.990000,19.990000,5.990000,1.000000,0.000000
1,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,5168467358507505407,4,2022-08-01,2022-08-01,12.000000,52.799999,38.158596,7.188600,7.200000,14.641404
2,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,3262679882836704514,4,2022-08-01,2022-08-01,2.000000,47.200001,42.640484,12.474483,0.000000,4.559516
3,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,14523659809755688,4,2022-07-08,2022-07-01,1.000000,23.500000,22.584913,5.498246,2.800000,0.915087
4,2204965430669363375,On Premise,Mexican Rest,30741,2204965430669363375,2888002190098573554,4,2022-10-24,2022-10-01,1.000000,25.000000,25.000000,7.500000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6515111,8795399024619655297,On Premise,Bar,80205,8795399024619655297,2000299989413890957,5,2022-09-11,2022-09-01,11.000004,274.760103,274.760103,80.555031,12.790008,0.000000
6515112,8795399024619655297,On Premise,Bar,80205,8795399024619655297,6182078584966538293,5,2022-09-11,2022-09-01,1.000002,25.500051,25.500051,7.666683,0.000000,0.000000
6515113,8795399024619655297,On Premise,Bar,80205,8795399024619655297,5800966932260176140,5,2022-09-11,2022-09-01,1.999992,51.979794,51.979794,11.994953,5.259979,0.000000
6515114,8795399024619655297,On Premise,Bar,80205,8795399024619655297,813787524868611759,5,2022-09-11,2022-09-01,3.000000,18.929993,18.929993,3.622493,0.000000,0.000000
6515115,8795399024619655297,On Premise,Bar,80205,8795399024619655297,7891860100939313524,5,2022-09-11,2022-09-01,1.000002,28.000055,28.000055,5.416677,4.430009,0.000000

In [90]:
df_pdv_transacao.columns

Index(['pdv', 'premise', 'categoria_pdv', 'zipcode', 'internal_store_id',
       'internal_product_id', 'distributor_id', 'transaction_date',
       'reference_date', 'quantity', 'gross_value', 'net_value',
       'gross_profit', 'discount', 'taxes'],
      dtype='object')

In [91]:
df_produto.columns

Index(['produto', 'categoria', 'descricao', 'tipos', 'label', 'subcategoria',
       'marca', 'fabricante'],
      dtype='object')

In [95]:
df_pdv_transacao.shape

(6515116, 15)

In [96]:
df_produto.shape

(192356316, 8)

In [94]:
df_pdv_transacao_produto = df_pdv_transacao.merge(df_produto, left_on=['internal_product_id'], right_on=['produto'])
df_pdv_transacao_produto

MemoryError: Unable to allocate 1.29 TiB for an array with shape (176709491268,) and data type int64

In [63]:
df_012

Empty DataFrame
Columns: [pdv, premise, categoria_pdv, zipcode, internal_store_id, internal_product_id, distributor_id, transaction_date, reference_date, quantity, gross_value, net_value, gross_profit, discount, taxes, produto, categoria, descricao, tipos, label, subcategoria, marca, fabricante]
Index: []

[0 rows x 23 columns]

In [ ]:
df_0['pdv'] = df_0['pdv'].astype(int)
df_0['premise'] = df_0['premise'].astype(str)
df_0['categoria_pdv'] = df_0['categoria_pdv'].astype(str)
df_0['zipcode'] = df_0['zipcode'].astype(int)

In [ ]:
df_raw_0.merge(df_raw_2, left_on='internal_store_id', right_on='pdv', how='inner')

In [ ]:
df_raw_01 = df_raw_0.merge(df_raw_2, left_on='internal_store_id', right_on='pdv', how='inner')
df_raw_01

KeyError: 'pdv'